pipeline {
    agent any
    environment {
        ENV_FILE = "/opt/project-env/project1.env"
    }

    stages {

        stage('Build & Start Services') {
            steps {
                sh 'export $(cat $ENV_FILE | xargs) && docker compose down || true'
                sh 'export $(cat $ENV_FILE | xargs) && docker compose up -d --build'
            }
        }

        stage('Test') {
            steps {
                sh 'export $(cat $ENV_FILE | xargs) && docker compose down || true'
                sh 'export $(cat $ENV_FILE | xargs) && docker compose up -d --build'
                sh 'sleep 10'
                sh 'export $(cat $ENV_FILE | xargs) && curl -f http://localhost:80/health'
            }
        }
    }
}