pipeline {
    agent any

    stages {

        stage('Build & Start Services') {
            steps {
                sh 'docker-compose down || true'
                sh 'docker-compose up -d --build'
            }
        }

        stage('Test') {
            steps {
                sh 'sleep 10'
                sh 'curl -f http://localhost:5000/health'
            }
        }
    }
}
